export enum ActionTypes {
  SET_CHARACTERS = "SET_CHARACTERS",
  SET_SEARCH_CHARACTERS = "SET_SEARCH_CHARACTERS",
  SET_LOADING = "SET_LOADING",
  SET_COUNT = "SET_COUNT",
  SET_SEARCH_LOADING = "SET_SEARCH_LOADING",
  SET_PAGE = "SET_PAGE",
  SET_FILTER = "SET_FILTER",
}
